### PR TITLE
fix: remove grep --exclude-dir option

### PR DESCRIPTION
**Pull request by darmshot**
I had have some trouble. Docker alpine hasn't option grep --exclude-dir

### CODE REVIEW

**Comment by awcodes** [comment]
Can you verify this fix for windows without docker?

**Comment by darmshot** [comment]
Sory but i haven't php environment on windows. I gess on windows work another function.

**Comment by awcodes** [comment]
@ryangjchandler @saade Can either of you confirm this PR wouldn't break anything?

**Comment by ryangjchandler** [comment]
> @ryangjchandler @saade Can either of you confirm this PR wouldn't break anything?

Think this'll be fine because it runs before the vendor folder has even been created right?

**Comment by awcodes** [comment]
> Think this'll be fine because it runs before the vendor folder has even been created right?

Yea, I just don't have a way to test the command on Windows, and I'm not sure if the linux command would be the same as window in this case, since both would get run against this method.

**Comment by saade** [comment]
I can test on windows without docker later tonight

**Comment by saade** [comment]
Looks like everything is OK. Tested on Windows without docker 👍🏼

**Pull request merged**
